[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sjrt = { path = "../sjrt" }
sjrt-net = { path = "../sjrt-net" }
clap = { workspace = true }
tokio = { version = "1.15.0", features = ["full"] }
nalgebra = "0.33"