[package]
name = "sjrt-net"
version = "0.1.0"
edition = "2024"

[dependencies]
sjrt = { path = "../sjrt" }
futures-util = "0.3"
image = { workspace = true }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "*" }
tonic = "0.6.2"
prost = "0.9"
serde = { workspace = true }
serde_qs = { workspace = true }
uuid = { version = "1", features = ["v4"] }
warp = "0.3.7"

[build-dependencies]
tonic-build = "0.6.2"
