[package]
name = "sjrt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sjrt-macro = { path = "../sjrt-macro" }

tokio = { version = "1.15.0", features = ["full"] }
futures = "0.3.19"
image = "0.25"
num = "*"
nalgebra = "0.33"
rand = "0.8.4"

serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "*"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rapier3d = { version = "0.22", features = ["simd-stable"] }

[target.'cfg(target_family = "wasm")'.dependencies]
rapier3d = { version = "0.22", features = [] }

[dev-dependencies]
clap = "*"
